packages:
  - mobile/
  - server/
  - web/

minRequiredVersion: 720

allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
